/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.14
 * Generated at: 2014-11-06 23:36:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\" class=\"no-js\">\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/reset.css\"> <!-- CSS reset -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/style.css\"> <!-- Gem style -->\n");
      out.write("\t<script src=\"js/modernizr.js\"></script> <!-- Modernizr -->\n");
      out.write("  \t\n");
      out.write("\t<title>VMall :: Virtual Shopping Mall</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<header>\n");
      out.write("\t\t<div id=\"logo\">\n");
      out.write("\t\t\t<img src=\"img/mall.png\" height=\"40px\" alt=\"Homepage\">\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"cd-hamburger-menu\"><a class=\"cd-img-replace\" href=\"#0\">Menu</a></div>\n");
      out.write("\t\t<div id=\"cd-cart-trigger\"><a class=\"cd-img-replace\" href=\"#0\">Cart</a></div>\n");
      out.write("\t</header>\n");
      out.write("\n");
      out.write("\t<nav id=\"main-nav\">\n");
      out.write("\t\t<ul>\n");
      out.write("\t\t\t<li><a href=\"#0\">Home</a></li>\n");
      out.write("\t\t\t<li><a href=\"#0\">Stores</a></li>\n");
      out.write("\t\t\t<li><a href=\"#0\">About</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<main>\n");
      out.write("\t\t<ul id=\"cd-gallery-items\" class=\"cd-container\">\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 1 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 2 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 3 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 4 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 5 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<center><img src=\"img/shop2.png\" alt=\"Preview image\"><center>\n");
      out.write("\t\t\t\t<br />\n");
      out.write("\t\t\t\t<center><span style=\"Font-size:20px;\"> Store 6 </span></center>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</ul> <!-- cd-gallery-items -->\n");
      out.write("\t</main>\n");
      out.write("\n");
      out.write("\t<div id=\"cd-shadow-layer\"></div>\n");
      out.write("\n");
      out.write("\t<div id=\"cd-cart\">\n");
      out.write("\t\t<h2>Cart</h2>\n");
      out.write("\t\t<ul class=\"cd-cart-items\">\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<span class=\"cd-qty\">1x</span> Product Name\n");
      out.write("\t\t\t\t<a href=\"#0\" class=\"cd-item-remove cd-img-replace\">Remove</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<span class=\"cd-qty\">1x</span> Product Name\n");
      out.write("\t\t\t\t<a href=\"#0\" class=\"cd-item-remove cd-img-replace\">Remove</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<span class=\"cd-qty\">1x</span> Product Name\n");
      out.write("\t\t\t\t<a href=\"#0\" class=\"cd-item-remove cd-img-replace\">Remove</a>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t</ul> <!-- cd-cart-items -->\n");
      out.write("\n");
      out.write("\t\t<div style=\"padding-top:30px;\"></div>\n");
      out.write("\n");
      out.write("\t\t<a href=\"#0\" class=\"checkout-btn\">Checkout</a>\n");
      out.write("\n");
      out.write("\t</div> <!-- cd-cart -->\n");
      out.write("<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js\"></script>\n");
      out.write("<script src=\"js/main.js\"></script> <!-- Gem jQuery -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
